#ifndef OKJVERSION_H
#define OKJVERSION_H

#define OKJ_VERSION_MAJOR 0
#define OKJ_VERSION_MINOR 5
#define OKJ_VERSION_BUILD 1
#define OKJ_VERSION_STRING "0.5.1"
#define OKJ_VERSION_BRANCH "unstable"

#endif //OKJVERSION_H
